import './sources/atm/gather.mjs';
import './sources/biedronka/gather.mjs';
import './sources/chatapolska/gather.mjs';
import './sources/inpost/gather.mjs';
import './sources/lidl/gather.mjs';
import './sources/mpk/gather.mjs';
import './sources/netto/gather.mjs';
import './sources/pharmacy/gather.mjs';
import './sources/zabka/gather.mjs';
