import './atm/gather.mjs';
import './biedronka/gather.mjs';
import './chatapolska/gather.mjs';
import './inpost/gather.mjs';
import './lidl/gather.mjs';
import './mpk/gather.mjs';
import './netto/gather.mjs';
import './pharmacy/gather.mjs';
import './zabka/gather.mjs';
